#pragma once
/**
 * For data model type, include this header is enough.
 */
#include "Common/ColumnTypes/CqlAscii.hpp"
#include "Common/ColumnTypes/CqlBigInt.hpp"
#include "Common/ColumnTypes/CqlBlob.hpp"
#include "Common/ColumnTypes/CqlBoolean.hpp"
#include "Common/ColumnTypes/CqlCounter.hpp"
#include "Common/ColumnTypes/CqlCustom.hpp"
#include "Common/ColumnTypes/CqlDate.hpp"
#include "Common/ColumnTypes/CqlDecimal.hpp"
#include "Common/ColumnTypes/CqlDouble.hpp"
#include "Common/ColumnTypes/CqlDuration.hpp"
#include "Common/ColumnTypes/CqlFloat.hpp"
#include "Common/ColumnTypes/CqlInet.hpp"
#include "Common/ColumnTypes/CqlInt.hpp"
#include "Common/ColumnTypes/CqlList.hpp"
#include "Common/ColumnTypes/CqlMap.hpp"
#include "Common/ColumnTypes/CqlSet.hpp"
#include "Common/ColumnTypes/CqlSmallInt.hpp"
#include "Common/ColumnTypes/CqlTime.hpp"
#include "Common/ColumnTypes/CqlTimestamp.hpp"
#include "Common/ColumnTypes/CqlTimeUuid.hpp"
#include "Common/ColumnTypes/CqlTinyInt.hpp"
#include "Common/ColumnTypes/CqlTuple.hpp"
#include "Common/ColumnTypes/CqlUdt.hpp"
#include "Common/ColumnTypes/CqlUuid.hpp"
#include "Common/ColumnTypes/CqlVarChar.hpp"
#include "Common/ColumnTypes/CqlVarInt.hpp"

